services:
  - type: web
    name: care-housemaid
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "gunicorn brain:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
